### ISSUE TITLE
Problems with writing 

### ISSUE THREAD

**Issue by dbryla** [dbryla/WebTextEditor#29]
Sometimes happens that I open 1-2 clients (on firefox) and if I type something I can see my changes (POSTs) in console (firebug), but after refresh they aren't applied, propagated to another client or saved to db.

**Comment by dbryla** [comment]
This issue can be related with new line tag. (<br>)

**Comment by Kelleth** [comment]
Two things:
1. Selected text + enter is bugged (somewhere in enter event processing in editor.js)
2. Fast key pressing is bugged (due to the fact that we compare body before key input with new one, and with fast pressing there may be a situation that it compares old body with new containing two more characters instead of one)

**Comment by Kelleth** [comment]
Fast key is probably fixed, every bug i noticed is in //TODO comments in editor.js on key press handlers.

**Comment by dbryla** [comment]
It seems that sometimes 'tags corruption' still happens, it should be investigated and fixed if possible. For every known bug which will be not fixed like pressing key after text selection should be written in some place. (Tips on application site or in documentation.)

**Comment by Kelleth** [comment]
Should be fixed with https://github.com/dbryla/WebTextEditor/commit/bbc4e4c93894200786f389c1425c6730aaa03cc6 . Variable containing body before operation was not updated on text alignment.
https://github.com/dbryla/WebTextEditor/commit/faf26e399a3185cf10b4cf5e2bf8e733498395da - this also fixes text formatting

**Comment by Kelleth** [comment]
https://github.com/dbryla/WebTextEditor/wiki/Bugs-related-to-text-editing
describes bugs related to document editing
